DriveShare/Controllers/MyFilesController.cs
using DriveShare.Models;
using DriveShare.Models.Enums;
using DriveShare.Repositories.Interfaces;
using DriveShare.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace DriveShare.Controllers;

[Authorize]
public class MyFilesController : Controller
{
    private readonly IFileData _fileDataRepo;

    public MyFilesController(IFileData fileDataRepo)
    {
        _fileDataRepo = fileDataRepo;
    }

    public IActionResult Index()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> GetUploads([FromForm] int start, string[] parameters, [FromForm] int length = 10)
    {
        try
        {
            var searchValue = Request.Form["search[value]"].FirstOrDefault();
            var columnOrder = Request.Form["order[0][column]"].FirstOrDefault();
            var sortColumn = Request.Form[string.Concat("columns[", columnOrder, "][name]")].FirstOrDefault();
            var sortDirectionPrm = Request.Form["order[0][dir]"].FirstOrDefault();
            SortOrder sortDirection = (sortDirectionPrm == "asc") ? SortOrder.Ascending : SortOrder.Descending;

            //Main query to select all user active files
            var filesQuery = _fileDataRepo.GetUserFilesQuery(GetUserId());

            //Search query for certain values if a search value is available
            if (!string.IsNullOrEmpty(searchValue))
            {
                filesQuery = _fileDataRepo.GetSearchQuery(filesQuery, searchValue);
            }

            //Select required columns for the viewModel
            var query = _fileDataRepo.GetSelectQuery(filesQuery);

            //If sort column is not defined, sort by creation date (desc)
            query = _fileDataRepo.GetSortQuery(query, sortColumn, sortDirection);

            var records = await _fileDataRepo.GetFilteredAsync(query, start, length);
            var totalCount = await _fileDataRepo.GetCountAsync(query);

            return Json(new
            {
                data = records,
                recordsFiltered = totalCount,
                recordsTotal = totalCount
            });
        }
        catch (Exception)
        {
            return StatusCode(500);
        }
    }

    [HttpGet]
    public IActionResult UploadFile()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> UploadFile(UploadFileViewModel model)
    {
        if (!ModelState.IsValid)
            return View(model);

        try
        {
            await _fileDataRepo.CreateAsync(model, GetUserId());
            return RedirectToAction(nameof(Index));
        }
        catch (Exception)
        {
            ModelState.AddModelError("", "An error occurred while saving the File, Please Try Again.");
        }

        return View(model);
    }

    private string GetUserId()
    {
        var userId = User.FindFirstValue(ClaimTypes.NameIdentifier).ToString();
        return userId;
    }

    [HttpDelete]
    public async Task<IActionResult> DeleteFile([FromBody] FileData model)
    {
        try
        {
            if (!await _fileDataRepo.DeleteAsync(model.Id, GetUserId()))
                return NotFound();
        }
        catch (Exception)
        {
            return StatusCode(StatusCodes.Status500InternalServerError);
        }

        return Json(new { RedirectUrl = "/MyFiles/Index" });
    }
}

DriveShare/Views/Shared/_FileCardsPartial.cshtml
@model IEnumerable<DriveShare.ViewModels.FileDataViewModel>

@{
    string[] imageList = { "png", "jpg", "jpeg", "gif", "tif", "tiff", "bmp", "ico", "Webp" };
}

<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-sm-6 col-md-4 col-lg-3 mb-4 d-flex align-items-stretch">
            <div class="card col-12">
                @if (imageList.Contains(item.ContentType))
                {
                    <img src="/Uploads/@item.FileSerial" class="card-img-top cursor-hover" alt="@item.FileName" />
                }
                else
                {
                    <img src="/images/Site Backgrounds/abstract.jpg" class="card-img-top cursor-hover" alt="@item.FileName" />
                }
                <div class="card-body d-flex flex-column text-center">
                    <h5 class="card-title text-primary">@item.FileName</h5>
                    <p class="card-text">@item.Description</p>
                    <p class="card-text"><small class="text-muted">Created on @item.CreatedOn.ToString("dd-MMM-yyyy HH:mm")</small></p>
                    <div class="row justify-content-center mx-1 mt-auto">
                        <a asp-controller="Home" asp-action="DownloadFile" asp-route-id="@item.Id" class="btn btn-outline-primary">@Localizer["Download"]</a>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

DriveShare/Views/Shared/_Layout.cshtml
@using System.Globalization

@{
    bool isArabic = CultureInfo.CurrentCulture.Name.StartsWith("ar");
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DriveShare</title>

    @*minified css file*@
    <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />

    @if (isArabic)
    {
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.rtl.min.css"
          integrity="sha384-gXt9imSW0VcJVHezoNQsP+TNrjYXoGcrqBZJpry9zJt8PCQjobwmhMGaDHTASo9N" crossorigin="anonymous">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@400;500&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="~/css/siteArabic.css" asp-append-version="true" />
    }
    <link rel="stylesheet" href="~/DriveShare.styles.css" asp-append-version="true" />

</head>
<body class="bg-light-gray">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid col-9 col-lg-10">
                <a class="navbar-brand text-primary fw-bold" asp-area="" asp-controller="Home" asp-action="Index">DriveShare</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">@Localizer["Home"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="BrowseFiles">@Localizer["Browse"]</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="MyFiles" asp-action="Index">@Localizer["MyFiles"]</a>
                            </li>
                        }
                        @*@if (User.IsInRole("Admin"))*@
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Home" asp-action="Index">Dashboard</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid col-9 col-lg-10" dir="@(isArabic?"rtl":"ltr")">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted">
        <div class="text-center">
            <p>&copy; 2022 <span class="fw-bold">DriveShare</span>, All Rights Reserved.</p>
        </div>
    </footer>
    @*minified scripts*@
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js" asp-append-version="true"></script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>